### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MichaelBowenSc** [BeastCode/VSCode-Angular-TypeScript-Snippets#1]
Create snippets for [**Angular Flex Layout**](https://github.com/angular/flex-layout).

**Comment by BeastCode** [comment]
Hi Mike,
that's a great idea! I added the following for you:
  
- ng-fx-import 
- ng-fx-row
- ng-fx-row-reverse
- ng-fx-column
- ng-fx-column-reverse
- ng-fx-item
- ng-fx-item-offset
- ng-fx-item-order 
- ng-fx-item-align 
- ng-fx-item-fill 

Take look at them and let me know if there is anything you miss or something that can be improved.

thanks /Mike
