### ISSUE TITLE
its not working anymore 

### ISSUE THREAD

**Issue by Dj-jom2x** [BeastCode/VSCode-Angular-TypeScript-Snippets#115]
![image](https://user-images.githubusercontent.com/12135498/67694870-16612800-f9df-11e9-85e4-a07d611a8ae9.png)

**Comment by Muromi-Rikka** [comment]
The release version 1.40 is also

**Comment by tohjg** [comment]
When I type `ng-`, expecting showing snippets but it does not.

**Comment by Dj-jom2x** [comment]
yeah let's keep this thread alive XDe

**Comment by jobvitral** [comment]
stop working -- vscode 1.40.0 mac version

**Comment by PeterShaws** [comment]
Not working on Windows either.
```
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by wizcas** [comment]
Yes it's not working in 1.14.0 along with flex layout support

**Comment by nbarkhina** [comment]
does anyone know how to build this project? we can try to fix it. when I do npm install however it doesn't even create a node_modules folder... normally when you create an extension there's a bunch of stuff it has to first download from npm. though i've never done a purely snippets type project

**Comment by sarmen22** [comment]
Version: 1.40.0 (user setup)

**Comment by BeastCode** [comment]
Hi Everyone! Thanks for reporting this. I’m currently 3,456.2 miles away from my computer, so open to any suggestions on how we can fix this. This extension has stopped working once in the past, but as soon as I updated the version number and published a new build it worked again. But without my computer it’s hard to verify :( However it’s possible to build the extension locally and try. Note this is not a regular npm project, but all snippets extensions for vscode look the same. Will add links in a few minutes.  /Mike

**Comment by BeastCode** [comment]
@Dj-jom2x Hey Mr DJ, thanks for finding this on the insider edition. I owe you some stickers, pm me and I’ll find a way to deliver them. /Mike

**Comment by Dj-jom2x** [comment]
> @Dj-jom2x Hey Mr DJ, thanks for finding this on the insider edition. I owe you some stickers, pm me and I’ll find a way to deliver them. /Mike

![C7yAk77VYAAr-BO](https://user-images.githubusercontent.com/12135498/68563732-7947ca00-0489-11ea-886a-0bc6c16f4de8.jpg)

this one? <3

**Comment by nbarkhina** [comment]
any eta on when this will be fixed?

**Comment by mikejoseph23** [comment]
I'll be patiently waiting for a fix. This has been a great extension and enjoy the vacation.

**Comment by pawelzwronek** [comment]
Quick manual fix is to replace files in `C:\Users\<YOUR USERNAME>\.vscode\extensions\mikael.angular-beastcode-8.0.10\snippets` with [these](https://github.com/pawelzwronek/VSCode-Angular-TypeScript-Snippets/tree/3dc2c349d776322de7712b8835a1f2b1694a866f/snippets)

**Comment by Dj-jom2x** [comment]
send a commit pr.. and merge it

**Comment by halildundar** [comment]
Thank you very much for those who contributed. Very good work.

**Comment by BeastCode** [comment]
I'm back home and released a fix, let me know if anyone still got issues or if you have any suggestions for enhancements or new snippets.

**Comment by Dj-jom2x** [comment]
finally

**Comment by BeastCode** [comment]
Sometimes life happens and of course Murphy's law proofs its existence just hours after I got on the plane... but something good came out of all this. Seeing all the names of the people missing the snippets gave me new energy to think about what's next.

**Comment by toddwseattle** [comment]
@beastcode I had to install and re-install to get to work; but now they are fine.  go figure.  Thanks for all that you do; and it's fun to have met you through the sea-town meetup.
