### ISSUE TITLE
VSCode version 1.40 is not working

### ISSUE THREAD

**Issue by lanxuexing** [BeastCode/VSCode-Angular-TypeScript-Snippets#117]
I have reduced the VSCode version to 1.39 and the plugin works fine.

The terminal runs the  `ng --version` command console output as follows.

` 
Angular CLI: 8.3.17
Node: 12.13.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.17
@angular-devkit/core         8.3.17
@angular-devkit/schematics   8.3.17
@schematics/angular          8.3.17
@schematics/update           0.803.17
rxjs                         6.4.0
`
Please help me with this, I'll be grateful.

**Comment by abz89** [comment]
That's exactly what happened to me. Updating VS Code recently then auto completions such as ng-* suddenly not working anymore even after reinstall the extension too

Thank You for useful extension btw

**Comment by guojianglin** [comment]
same issue as in #115

**Comment by iconio** [comment]
On the same boat!

**Comment by khanghyxda** [comment]
same issue

**Comment by rip222** [comment]
same

**Comment by vip20** [comment]
Same issue for me as well, downgraded to 1.39.2 and it works.

**Comment by reynave** [comment]
Same issue for me VSC ver 1.40.1

**Comment by intkhabahmed** [comment]
Same issue for me as well after updating VSCode to 1.40.1, any solution yet other than downgrading the vscode

**Comment by jordankkk** [comment]
same with 1.40.1

**Comment by MoAsmar** [comment]
duplicate issue, already created here [its not working anymore](https://github.com/BeastCode/VSCode-Angular-TypeScript-Snippets/issues/115)

**Comment by BeastCode** [comment]
I'm back home and released a fix, let me know if anyone still got issues or if you have any suggestions for enhancements or new snippets.

**Comment by nbarkhina** [comment]
yep it works now thanks!
