### ISSUE TITLE
Html autocomplete doesn't remove initial less than character

### ISSUE THREAD

**Issue by jbbasson** [BeastCode/VSCode-Angular-TypeScript-Snippets#118]
Noticed when creating an angular container, the initial opening less than character is not removed when using intellisense suggestion. Same with a greater than closing character.

![image](https://user-images.githubusercontent.com/5420676/68913464-5e938080-0729-11ea-9e16-b5b30551d1ee.png)

**Comment by BeastCode** [comment]
Hi,

you can type any part of:
   ng-container
and it will be replaced with 
 <ng-container></ng-container>

All snippets in VSCode work the same way, can't do anything about characters before the keyword ng-container
