### ISSUE TITLE
ngswitch shortcut generates a incorrect html template

### ISSUE THREAD

**Issue by guojianglin** [BeastCode/VSCode-Angular-TypeScript-Snippets#124]
![image](https://user-images.githubusercontent.com/48773605/71468977-bb8f5580-2802-11ea-804e-6c18ee42d7d4.png)

![image](https://user-images.githubusercontent.com/48773605/71468993-cc3fcb80-2802-11ea-8585-ca084562231c.png)

As you can see, when I typed in the ng-switch shortcut, it generates a semantically incorrect html template.

When I checked the MDN, I'm sure that an inline element like `span` shouldn't nest a block element like `p`:

![image](https://user-images.githubusercontent.com/48773605/71469842-5ee16a00-2805-11ea-9079-14a8655d3f81.png)

![image](https://user-images.githubusercontent.com/48773605/71469780-2e99cb80-2805-11ea-911a-ff934c14d031.png)

**Comment by BeastCode** [comment]
Thanks, I enhanced the snippet!
