### ISSUE TITLE
m-spinner-indeterminate produces wrong code

### ISSUE THREAD

**Issue by craigsh** [BeastCode/VSCode-Angular-TypeScript-Snippets#127]
When using m-spinner-indeterminate, it produces the following:

```
<mat-spinner
	[mode]="indeterminate">
</mat-spinner>
```

There shouldn't be square brackets around mode. It should produce:

`<mat-spinner	mode="indeterminate"></mat-spinner>`

**Comment by BeastCode** [comment]
You are right, thanks!

**Comment by BeastCode** [comment]
Found it in a second place, fixed
