### ISSUE TITLE
app keeps crashing

### ISSUE THREAD

**Issue by rue-elwahishi** [BeastCode/VSCode-Angular-TypeScript-Snippets#128]
Issue Type: <b>Bug</b>

Typescript died 5 times keeps crashing Vcode.

Extension version: 8.1.2
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.56GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by cgatian** [comment]
How is this related to this package?

**Comment by BeastCode** [comment]
Closing

**Comment by cgatian** [comment]
About time beast
