### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by mackelito** [BeastCode/VSCode-Angular-TypeScript-Snippets#13]
Would be really nice if we could get a proper changelog :)

**Comment by BeastCode** [comment]
Tjena Markus!

Visst kan jag lagga till en changelog :)

mvh /Micke

**Comment by mackelito** [comment]
Gissa om jag blev förvånad när jag läste en notification från github på svenska! :D 

Would be awesome! 👍  
Always nice to see if there are any new cool things that I can use!
Wat! ;)

**Comment by BeastCode** [comment]
Change log is live  4.0.6
