### ISSUE TITLE
Angular Material Table - some table tags are crashing code syntax

### ISSUE THREAD

**Issue by mgrzegorczyk** [BeastCode/VSCode-Angular-TypeScript-Snippets#131]
When I use tags e.g.: `*matHeaderCellDef`, `*matCellDef="let element"` syntax is crashing:
![wrong](https://user-images.githubusercontent.com/24443627/74316434-cfbef000-4d79-11ea-9ec7-dea7fcaffd64.jpg)

After remove tags with * prefix everything is ok:
![ok](https://user-images.githubusercontent.com/24443627/74316639-37753b00-4d7a-11ea-800d-dd55b658927e.png)

VSCode version: 1.42.0
Snippets version: 8.1.2

**Comment by michael-letcher** [comment]
@mgrzegorczyk 

I wouldn't say the snippet is incorrect as it is based off the examples here:
https://material.angular.io/components/table/examples

This would be a bug for the plugin that is providing your syntax.

**Comment by BeastCode** [comment]
fixing now
