### ISSUE TITLE
NGRX redesigned

### ISSUE THREAD

**Issue by michael-letcher** [BeastCode/VSCode-Angular-TypeScript-Snippets#135]
https://medium.com/angular-in-depth/ngrx-action-creators-redesigned-d396960e46da

I'd be happy to add the redesigned patterns.

@BeastCode  would you like to keep the old ones or can I replace them?

Changes needed
- ngrx-action-const (remove)
- ngrx-action-creator (update)
- ngrx-action-creator-enum (remove)
- ngrx-actions (update)
- ngrx-actiontype-enum (remove)
- ngrx-actiontypes-enum (remove)
- ngrx-effect (NEW - add a single effect)
- ngrx-effect-creator (RENAMED from ngrx-effect, update)
- ngrx-module (remove, outdated and really not that useful, many will have used the CLI)
- ngrx-reducer (update)
- ngrx-util (leave, never needed this so I cannot comment if it's still relevant)

**Comment by BeastCode** [comment]
That would be great and yes you can replace the old ones.

**Comment by BeastCode** [comment]
Had some extra time...looked through your commits and lifted in your new snippets into typescript.json.

Take a look and see if I missed anything :)

**Comment by BeastCode** [comment]
Thanks!

**Comment by michael-letcher** [comment]
@BeastCode looks good to me
