### ISSUE TITLE
add support for "ng-router-attribute"

### ISSUE THREAD

**Issue by mackelito** [BeastCode/VSCode-Angular-TypeScript-Snippets#14]
Right now, ng-router-link will give us 
` <a [routerLink]="[ '/path', routeParam ]">`

Would like to see support for adding just the attribute eg.
ng-router-attribute -> `[routerLink]="[ '/path', routeParam ]"`

Most of the time I use it to add a link on a already existing element :)

**Comment by BeastCode** [comment]
Added snippet and published 4.0.6 to the market
