### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by doggy8088** [BeastCode/VSCode-Angular-TypeScript-Snippets#144]
Hi @BeastCode, the [Angular 10 Snippets - TypeScript, Html, Angular Material, ngRx, RxJS & Flex Layout](https://marketplace.visualstudio.com/items?itemName=Mikael.Angular-BeastCode) extension seems not updating for a long time. Is it possible to release new version?

**Comment by doggy8088** [comment]
Hi @BeastCode, are you there?

**Comment by BeastCode** [comment]
Hi Will, traveling right now, but will be back home in a week. Got a bunch
of updates coming. So hopefully you’ll see something soon.

Hope everything is well /Mike

**Comment by BeastCode** [comment]
Hi @doggy8088,
hope everything is well.
I'm reviewing some snippets here and thinking half of them should be deleted... tempted to to a major rewrite...are there anything you still use?

**Comment by doggy8088** [comment]
@BeastCode I agreed. I think some of the snippets can be deleted because the Angular Language Service already doing the good job.
