### ISSUE TITLE
Material Snippets Outdated

### ISSUE THREAD

**Issue by cgatian** [BeastCode/VSCode-Angular-TypeScript-Snippets#16]
I think some of these snippets incorrect.  For example:

`md-button:simple`

Generates: 
```
<md-button aria-label="button-label"> button-label </md-button>
```
md-button is no longer component, and a button element should be used with md-button directive.
```
<button md-button></button>
```

This was the first snippet I came across.  There may be others that are outdated.

**Comment by BeastCode** [comment]
I haven't added any snippets for Material design, so I think you're looking at another plugin...
but maybe we should add some :)

**Comment by cgatian** [comment]
{headsmack} You're right.

**Comment by BeastCode** [comment]
No worries :)

Not an issue, closing!
