### ISSUE TITLE
Rename ng-module and ng-module-template

### ISSUE THREAD

**Issue by cgatian** [BeastCode/VSCode-Angular-TypeScript-Snippets#17]
I think it would be more convenient if `ng-module` used the `ng-module-template`'s template.

Basically:
rename `ng-module-template` to `ng-module`
rename `ng-module-template` to `ng-module:root`.

Currently, you are more likely to use `ng-module-template` much more than the `ng-module`.  Defaulting `ng-module` to the template version makes more sense.

**Comment by BeastCode** [comment]
Sounds good, I'll rename them!

**Comment by BeastCode** [comment]
Fixed in v4.0.7
