### ISSUE TITLE
Where are all the material snippets?

### ISSUE THREAD

**Issue by mackelito** [BeastCode/VSCode-Angular-TypeScript-Snippets#18]
Currently we just have toolbar.. what about the rest? :)
Love it that you are adding materials as well 👍 

Any chance that you might add Flex Layout as well?
https://github.com/angular/flex-layout

**Comment by mackelito** [comment]
Ah.. just saw that you do have flex.. what about renaming the prefix from ng to fx? ;)

**Comment by BeastCode** [comment]
:)

Are you sure you need more than a toolbar ;)
I guess I'll add some more...

**Comment by BeastCode** [comment]
I Will create separate issues for each material design snippet
