### ISSUE TITLE
ngOnChanges should implement SimpleChange interface

### ISSUE THREAD

**Issue by cgatian** [BeastCode/VSCode-Angular-TypeScript-Snippets#2]
Update the code snippet for ngOnChanges by providing an interface for changeRecord.  Currently this outputs an `any` type and could be improved.

Below is the proposed change:
```
  ngOnChanges(changeRecord: {[propKey: string]: SimpleChange})
    //Called before any other lifecycle hook. Use it to inject dependencies, but avoid any serious work here.
    //Add 'implements OnChanges' to the class.
  }
```

**Comment by BeastCode** [comment]
Thanks for the suggestion!

I've added it to v2.4.3 and published it. Let me know what you think.

thanks /Mike

**Comment by cgatian** [comment]
@BeastCode Damn you truly are BeastCode!
