### ISSUE TITLE
Add Material snippet for SVG icon

### ISSUE THREAD

**Issue by BeastCode** [BeastCode/VSCode-Angular-TypeScript-Snippets#20]
Prefix: m-icon-svg
File: src/snippets.json
Example:
<md-icon svgIcon="animals:cat"></md-icon>

**Comment by azjkjensen** [comment]
@BeastCode check out my PR for this and let me know what you think!

**Comment by BeastCode** [comment]
Looks good, merging

**Comment by orcutt989** [comment]
Please close - still appears in search for first-timers-only open issues.

**Comment by BeastCode** [comment]
Snippet published in Version 4.1.13
