### ISSUE TITLE
Add Material snippet for SVG src

### ISSUE THREAD

**Issue by BeastCode** [BeastCode/VSCode-Angular-TypeScript-Snippets#21]
Prefix: m-icon-svg-src

File: src/snippets.json

Example:
<md-icon svgSrc="assets/arrow.svg"></md-icon>

**Comment by azjkjensen** [comment]
@BeastCode I'd love to take this one on. Is the snippet you want just like `src="${src}.svg"`? Is this just for the src attribute on any element, with an svg file as the value?

**Comment by BeastCode** [comment]
Hi and thanks for looking at the issues! I apparently forgot to add the example, but i was thinking:  "md-icon element, with an svg file as the value".

thanks /Mike

**Comment by azjkjensen** [comment]
Okay it looks like [svgSrc has been deprecated](https://github.com/angular/material2/issues/2521#issuecomment-270401467), so I'm going to go ahead and close this issue for now, and make a PR for the svgIcon one you've created.

**Comment by orcutt989** [comment]
Please close - still shows up in search for first-timers-only open issues.
