### ISSUE TITLE
ng-class snippet should be the same as ng-style

### ISSUE THREAD

**Issue by doggy8088** [BeastCode/VSCode-Angular-TypeScript-Snippets#25]
The `ng-style` snippet is:

> [ngStyle]="{'property': expression}"

The 'ng-class` snippet is:

> [ngClass]="{class}"

I think the `ng-class` snippet should be just like `ng-style` snippet which is more meaningful.

**Comment by BeastCode** [comment]
Which ones do you think is relevant?

<some-element [ngClass]="'first second'">...</some-element>
<some-element [ngClass]="['first', 'second']">...</some-element>
<some-element [ngClass]="{'first': true, 'second': true, 'third': false}">...</some-element>
<some-element [ngClass]="stringExp|arrayExp|objExp">...</some-element>
<some-element [ngClass]="{'class1 class2 class3' : true}">...</some-element>

**Comment by doggy8088** [comment]
I choose `<some-element [ngClass]="{'className': true}">`

**Comment by doggy8088** [comment]
@BeastCode Do you need an PR? I can help if you need.

**Comment by BeastCode** [comment]
Fixed in v4.2.9
