### ISSUE TITLE
Use SimpleChanges for ngOnChanges

### ISSUE THREAD

**Issue by cgatian** [BeastCode/VSCode-Angular-TypeScript-Snippets#27]
snippet: `ng-ngOnChanges`

Update from:
`ngOnChanges(changes: {[propKey: string]: SimpleChange}) {`
to:
`ngOnChanges(changes: SimpleChanges) {`

Looks like in 4.0 they created a type alias, SimpleChanges.

**Comment by BeastCode** [comment]
Checked in fix

**Comment by BeastCode** [comment]
Published: v4.1.17

**Comment by cgatian** [comment]
The beast is real!!!
