### ISSUE TITLE
Snippets no longer displaying

### ISSUE THREAD

**Issue by cgatian** [BeastCode/VSCode-Angular-TypeScript-Snippets#34]
I've tried uninstalling/installing VS Code, clearing my `Users/AppData/Roaming` cache. Nothing seems to work. Was working Friday.

Installed John Papa's snippets (regrettably) and they work.

VSCode: 1.14.2
Windows 10

**Comment by BeastCode** [comment]
That's weird, I'll take a look at it.

**Comment by insta-code1** [comment]
Yep Say here, I think vs code released a new update...

**Comment by cgatian** [comment]
I saw snippets.html was removed in last check in. Don't know if that
matters.

**Comment by BeastCode** [comment]
Hi, Publish a new version: 4.2.21

**Comment by BeastCode** [comment]
FYI, there were a missing bracket that resulted in the generated snippets files to be empty. Will add a check to the build script.

**Comment by BeastCode** [comment]
Verified on both old (1.8) and new version of VSCODE
