### ISSUE TITLE
ng-router-featuremodule fixes

### ISSUE THREAD

**Issue by cgatian** [BeastCode/VSCode-Angular-TypeScript-Snippets#35]
`ng-router-featuremodule` issues:

* Missing import to NgModule

```
import { NgModule } from '@angular/core';
```
* import from `'./routes'` is not found and should be removed

Output:
```
import { RouterModule } from '@angular/router';
import { routes } from './routes';

const routes: Routes = [
    { path: 'path', component: FeatureComponent }
];

@NgModule({
    imports: [RouterModule.forChild(routes)],
    exports: [RouterModule]
})
export class FeatureRoutingModule {}
```

**Comment by BeastCode** [comment]
One more, Need to import Routes from the angular/router

**Comment by BeastCode** [comment]
Thanks Chaz!!!

Fixed and release, so take a look.

 If you ever want to submit a pull request instead of writing this issue, you can always do that. If not I'm more then happy to keep adding them for you.

**Comment by cgatian** [comment]
It might be just as productive if I do that. Usually Im coding and mentally
avoided the task switch.

**Comment by BeastCode** [comment]
No worries, but you should now you have the option if you want to. But keep adding them and I'll fix em. What should we add next?
