### ISSUE TITLE
Component Cursor positions off

### ISSUE THREAD

**Issue by cgatian** [BeastCode/VSCode-Angular-TypeScript-Snippets#39]
When creating a `ng-component` the cursor positions are incorrect. 

`ng-component-inline` should also be checked

**Comment by cgatian** [comment]
@BeastCode I can get to this tonight

**Comment by BeastCode** [comment]
Great, thanks!

**Comment by BeastCode** [comment]
The word prefix broke the generation of the readme file, so I temporarily replaced prefix with "app" and published a new build tonight. I'll switch back once the build script is updated.
