### ISSUE TITLE
Add commitizen with custom commit process

### ISSUE THREAD

**Issue by cgatian** [BeastCode/VSCode-Angular-TypeScript-Snippets#41]
Commitizen is a tool for standardizing commit messages. It would be slick if we could make our commit messages not only consistent, but provide details into what snippets were updated via commit message.

**Comment by cgatian** [comment]
Beast are you OK with this? I would like to take this on. Im  thinking of using [this](https://github.com/leonardoanalista/cz-customizable) and making some basic rules. 

Take a look at let me know what youre thinking

**Comment by cgatian** [comment]
Do you have ideas around the types of commit messages? 

Im thinking, docs, build, ng-snips, mat-sips, ect

**Comment by BeastCode** [comment]
Sounds good, I also took a look a commitizen and it looks good as well!
