### ISSUE TITLE
Create contribution guide

### ISSUE THREAD

**Issue by cgatian** [BeastCode/VSCode-Angular-TypeScript-Snippets#42]
Provide a document on how to contribute, which includes snippet best practices.

**Comment by BeastCode** [comment]
This is a great idea. There is a lost of things we can use from your last pull request as well.

**Comment by cgatian** [comment]
I can take this on

**Comment by BeastCode** [comment]
Awesome

**Comment by cgatian** [comment]
@BeastCode sorry been a bit busy. Have some time off this week to tackle this

**Comment by BeastCode** [comment]
No worries!!!
