### ISSUE TITLE
Create Snippet for ng-test-service

### ISSUE THREAD

**Issue by BeastCode** [BeastCode/VSCode-Angular-TypeScript-Snippets#43]
Add the new snippet to the snippets.json in the source folder, everything else will be generated automatically later on. See existing snippets for examples.

**Comment by tikishabudin** [comment]
May I take a stab at this?

**Comment by raidenfreeman** [comment]
What should ng-test-service do? Generate a karma test for a service?

**Comment by BeastCode** [comment]
@tikishabudin Sorry for missing your comment, wish I saw it in March
