### ISSUE TITLE
Create snippet for mat-accordion

### ISSUE THREAD

**Issue by BeastCode** [BeastCode/VSCode-Angular-TypeScript-Snippets#48]
Add the new snippet to the snippets.json in the source folder, everything else will be generated automatically later on. See existing snippets for examples.

**Comment by raidenfreeman** [comment]
Shouldn't this be closed?

**Comment by BeastCode** [comment]
Yes, it looks like you just put the number #48 in and not 
Closes: #48
If you want credit for just add that line to your other PR. If not I can close it.
