### ISSUE TITLE
ng-import

### ISSUE THREAD

**Issue by HerveGagnon** [BeastCode/VSCode-Angular-TypeScript-Snippets#53]
ng-import generates "import ${module or component} from 'path';"
Is there a way to generate "import {  } from 'path';" instead?

**Comment by BeastCode** [comment]
Hi Herve,

It looks like spaces between the brackets are breaking the snippet.
I'll put in a quick fix for you.

Thanks /Mike

**Comment by BeastCode** [comment]
Fix, been published!
