### ISSUE TITLE
ng-fx-col should not include the actual div

### ISSUE THREAD

**Issue by mackelito** [BeastCode/VSCode-Angular-TypeScript-Snippets#56]
using "ng-fx-col" results in:
```
<div fxLayout="column" fxLayoutAlign="${start|center|end|space-around|space-between} ${start|center|end|stretch}" fxLayoutGap="gappx">
  
</div>
```

But I more often find myself needing just the attributes.
I would suggest that ng-fx should only apply the attributes as it can be used on other elements as well.. not only divs

**Comment by BeastCode** [comment]
Published fix
