### ISSUE TITLE
Create snippet for Material Divider with Inset (mat-divider)

### ISSUE THREAD

**Issue by BeastCode** [BeastCode/VSCode-Angular-TypeScript-Snippets#62]
Create snippet for <mat-divider [inset]="true"></mat-divider>

Add the new snippet to the snippets.json in the source folder, everything else will be generated automatically later on. See existing snippets for examples.

**Comment by tikishabudin** [comment]
Just created a pull request for this. Please do let me know if I'm doing this correctly. If not, let me know what I did wrong. Thank you

**Comment by BeastCode** [comment]
Looks great, thanks!

**Comment by BeastCode** [comment]
Published: Version 5.2.17
