### ISSUE TITLE
ng-component-inline invalid

### ISSUE THREAD

**Issue by cgatian** [BeastCode/VSCode-Angular-TypeScript-Snippets#72]
**Snippet:** `ng-component-inline`

**Description:** This snippet produces extra characters `:void {}` within the class. Looks like the `ngOnInit` is missing from the signature.

**Current Output:**
```
@Component({
  selector: 'app-name',
  template: ``,
  styles: [``]
})
export class NameComponent implements OnInit {
  constructor() { }

  : void { }
}
```

**Comment by BeastCode** [comment]
I added ngOnInit... not sure where it went.

**Comment by BeastCode** [comment]
Thanks Chaz! It's been published.
