### ISSUE TITLE
Don't see anything when adding "m-card" snippet

### ISSUE THREAD

**Issue by marc-schneider** [BeastCode/VSCode-Angular-TypeScript-Snippets#75]
Hi, when i try your snippet with `m-card`, thats create `<mat-card></mat-card>` but i don't see anything on my html page.
I try with a `ng-for-li` and with this i see my data.

My example is : 
```
<mat-card>

  <mat-card-header>
    <mat-card-title>This is the title</mat-card-title>
    <mat-card-subtitle>This is a description</mat-card-subtitle>
  </mat-card-header>

  <mat-card-content>
    This is my content
  </mat-card-content>

  <mat-card-actions>
    <button mat-button>Ok</button>
  </mat-card-actions>

</mat-card>
```

Best Regards

**Comment by yalcinumut** [comment]
When I try using this its works fine. For using angular material you need to install npm packages did you installed it? If you didn't install it maybe that's the problem. Check the link below ;
https://material.angular.io/guide/getting-started
https://material.angular.io/components/card/examples

**Comment by rahul-1903** [comment]
May be you would not have imported the MatCardModule from @angular/material/card in app.module.ts

**Comment by BeastCode** [comment]
Please add comment if you still need help
