### ISSUE TITLE
How to use pwa-manifest?

### ISSUE THREAD

**Issue by atiris** [BeastCode/VSCode-Angular-TypeScript-Snippets#77]
What is this snippet `pwa-manifest` and when (in which files) can I use it?

I've tried all commands sequentially, but I do not know how to call this one.  
This snippet is included in the version 6.0.0 according to https://github.com/BeastCode/VSCode-Angular-TypeScript-Snippets/blob/41bd55cab3621668d452098b4b0c8b573b4d0867/CHANGELOG.md

**Comment by BeastCode** [comment]
Hi Jozef,

the pwa-manifest was causing an issue generating the snippets, so I temporary disabled it, but it's back now in the version i published today.

It's meant to be used in the manifest.json file, see https://developers.google.com/web/fundamentals/web-app-manifest/ for more info.

Let me know how it goes and if you have any suggestions for improvements.

thanks /Mikael

**Comment by atiris** [comment]
Hi Mikael,
yes, after testing in version 6.2.8 everything works now.
Feel free to close this bug. Thanks

---

If you asking for improvements suggestion, I thought this:

Now the snippets looks like:
![image](https://user-images.githubusercontent.com/10474618/43944290-b1dc5210-9c7e-11e8-987a-951a77748502.png)

I experimeted with extended description. It would be good if snippet can directly referred to documentation and an example of use:

```json
{
  "prefix":"ng-for",
  "description":"For-loop directive - [Documentation](<https://angular.io/api/common/NgForOf>) | [Example](<https://angular.io/guide/displaying-data#showing-an-array-property-with-ngfor>)",
  "types":"typescript, html",
  "body":["*ngFor=\"let ${item} of ${items}\"$0"]
}
```
But I see this is not possible on snippets now. If you do this in class, you get:

![image](https://user-images.githubusercontent.com/10474618/43945544-ace989e0-9c82-11e8-8a16-b9112d15fcb4.png)

And user can CTRL+CLICK to open documentation and example directly. I can't find any solution for this with snippets but you can maybe hit something if it is possible.

Greetings
Jozef
