### ISSUE TITLE
ng-model does not have a code snippet, can we have that one too ?

### ISSUE THREAD

**Issue by ravishankarkota2017** [BeastCode/VSCode-Angular-TypeScript-Snippets#78]
I have seen very useful snippets for ng-if, ng-for but surprisingly ng-model snippet for angular is missing, can we get this added too? ng-model addition makes this extension awesome.

**Comment by BeastCode** [comment]
Hi Ravi,

how about something like
ng-model  ->    [(ngModel)]="name" 
or what were you thinking?

thanks /Mike

**Comment by BeastCode** [comment]
I published a new version  for you if you want to test it out. Let me know what else we can add :)

thanks again /Mike

**Comment by BeastCode** [comment]
Closing, let me know if you have any other suggestions on how to improve it.
